/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FormacionesRouteImport } from './routes/formaciones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AromaterapiaRouteImport } from './routes/aromaterapia'
import { Route as AcompanamientoRouteImport } from './routes/acompanamiento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacionesRoute = FormacionesRouteImport.update({
  id: '/formaciones',
  path: '/formaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AromaterapiaRoute = AromaterapiaRouteImport.update({
  id: '/aromaterapia',
  path: '/aromaterapia',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanamientoRoute = AcompanamientoRouteImport.update({
  id: '/acompanamiento',
  path: '/acompanamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanamiento': typeof AcompanamientoRoute
  '/aromaterapia': typeof AromaterapiaRoute
  '/contacto': typeof ContactoRoute
  '/formaciones': typeof FormacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanamiento': typeof AcompanamientoRoute
  '/aromaterapia': typeof AromaterapiaRoute
  '/contacto': typeof ContactoRoute
  '/formaciones': typeof FormacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanamiento': typeof AcompanamientoRoute
  '/aromaterapia': typeof AromaterapiaRoute
  '/contacto': typeof ContactoRoute
  '/formaciones': typeof FormacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanamiento'
    | '/aromaterapia'
    | '/contacto'
    | '/formaciones'
    | '/sitemap.xml'
    | '/sobre'
    | '/productos/$slug'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanamiento'
    | '/aromaterapia'
    | '/contacto'
    | '/formaciones'
    | '/sitemap.xml'
    | '/sobre'
    | '/productos/$slug'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/acompanamiento'
    | '/aromaterapia'
    | '/contacto'
    | '/formaciones'
    | '/sitemap.xml'
    | '/sobre'
    | '/productos/$slug'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanamientoRoute: typeof AcompanamientoRoute
  AromaterapiaRoute: typeof AromaterapiaRoute
  ContactoRoute: typeof ContactoRoute
  FormacionesRoute: typeof FormacionesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formaciones': {
      id: '/formaciones'
      path: '/formaciones'
      fullPath: '/formaciones'
      preLoaderRoute: typeof FormacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aromaterapia': {
      id: '/aromaterapia'
      path: '/aromaterapia'
      fullPath: '/aromaterapia'
      preLoaderRoute: typeof AromaterapiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanamiento': {
      id: '/acompanamiento'
      path: '/acompanamiento'
      fullPath: '/acompanamiento'
      preLoaderRoute: typeof AcompanamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanamientoRoute: AcompanamientoRoute,
  AromaterapiaRoute: AromaterapiaRoute,
  ContactoRoute: ContactoRoute,
  FormacionesRoute: FormacionesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ProductosSlugRoute: ProductosSlugRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
